function devignettefolder(folder,calibrationmatrix)
%run through a folder of tifs and devignette all of them.
%creates a new file "foo-devig.tif" for every file "foo.tif"

%correct for vignetting for all .tifs in a folder
%needs a calibrationmatrix generated by devignettecalibrate.m
%
%Saul Kato
%04/18/2013

if nargin<2
    disp('using default calibration matrix');
    ps=load('devignettecal.mat');
    calibrationmatrix=ps.p;
end

if nargin<1
    folder=pwd;
end

cd(folder);
fnames=dir([folder '/*.tif']);

mkdir('devig');

for i=1:length(fnames)
    tifname=fnames(i).name;   
    X=tiffread2(tifname);
    Xout=devignette(X.data,calibrationmatrix);
    outputfilename=['devig/' tifname(1:end-4) '-devig.tif'];
    imwrite(Xout,outputfilename,'tif','Compression','none')
end


function imgout=devignette(imgin,calibrationmatrix)

imgout=zeros(size(imgin),'uint16');
for i=1:size(imgin,1)
    for j=1:size(imgin,2)
        imgout(i,j)=uint16((double(imgin(i,j))-calibrationmatrix(2,i,j))/calibrationmatrix(1,i,j));
    end
end